- name: play1
- hosts: tomcat
  become: true
  tasks:
    - name: Download war file 
      maven_artifact: 
       group_id: com.mt
       artifact_id: java-web-app 
       extension: war 
       version: 1.0.0 
       repository_url: "http://43.204.22.243:8081/repository/test-release/" 
       username: admin
       password: admin123
       dest: "/tmp/java-web-app-1.0.0.war" 
       mode: '0755'
    - name: copying file to tomcat server
      copy:
       src: /tmp/java-web-app-1.0.0.war
       dest: /opt/tomcat10/webapps/
       remote_src: yes
       notify: Restart tomcat
 handlers:
 - name: "Restart tomcat"
   shell: tomcatup
