- name: play1
- hosts: tomcat
  become: true
  tasks:
    - name: copying file to tomcat server
      copy:
       src: /var/lib/jenkins/workspace/Pipeline-Job/target/java-web-app-1.0.0.war
       dest: /opt/tomcat10/webapps/
      notify: "Restart tomcat"
      handlers:
    - name: "Restart tomcat"
      shell: tomcatdown
      shell: tomcatup
